In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [34]:
data=pd.read_csv('Churn_Modelling.csv')

In [35]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [36]:
##Preprocess the data 
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [37]:
#Encode categorical variable
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [38]:
data['Geography'].unique()

<ArrowStringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str

In [39]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])

In [40]:
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [41]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [42]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [43]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [44]:
##combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [45]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [46]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [47]:
##divide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

In [48]:
##split the data 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [49]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [50]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [51]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [52]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Implementation

In [53]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [54]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),##HL1 connected with input layer
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid') 
])

In [55]:
X_train.shape[1]

12

In [56]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [57]:
##compile the model

In [58]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [59]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])
#same as model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [60]:
#set up the tensorboard

In [61]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir='logs/fit'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [62]:
#set up early stopping 
#we can train it for multiple epochs 
#after certain number of epochs the loss function doesn't decrease we set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [63]:
###training the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 3ms/step - loss: 0.4000 - accuracy: 0.8306 - val_loss: 0.3540 - val_accuracy: 0.8620
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8590 - val_loss: 0.3494 - val_accuracy: 0.8585
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8566 - val_loss: 0.3487 - val_accuracy: 0.8565
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3429 - accuracy: 0.8591 - val_loss: 0.3624 - val_accuracy: 0.8555
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8611 - val_loss: 0.3466 - val_accuracy: 0.8610
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8591 - val_loss: 0.3463 - val_accuracy: 0.8635
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8615 - val_loss: 0.3512 - val_accuracy: 0.8585
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3386 - accuracy: 0.8633 - val_loss: 0.3364 - val_accuracy: 0.8630
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8621 - val_loss: 0.3456 - val_accuracy: 0.8530
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8639 - val_loss: 0.3463 - val_accuracy: 0.8570
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3290 - accuracy: 0.8634 - val_loss: 0.3392 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3254 - accuracy: 0.8650 - val_loss: 0.3442 - val_accuracy: 0.8630
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3243 - accuracy: 0.8677 - val_loss: 0.3490 - val_accuracy: 0.8570
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 0.8661 - val_loss: 0.3480 - val_accuracy: 0.8555
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3187 - accuracy: 0.8677 - val_loss: 0.3469 - val_accuracy: 0.8580
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3179 - accuracy: 0.8705 - val_loss: 0.3512 - val_accuracy: 0.8545
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3160 - accuracy: 0.8709 - val_loss: 0.3529 - val_accuracy: 0.8660
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3141 - accuracy: 0.8715 - val_loss: 0.3530 - val_accuracy: 0.8590

In [64]:
model.save('model.h5')
##h5 file is compatible with keras

e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [65]:
##load tensorboard extension 
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [66]:
%load_ext tensorboard
import pkg_resources
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 32408), started 8:17:28 ago. (Use '!kill 32408' to kill it.)

In [67]:
pip install setuptools==69.5.1

Requirement already satisfied: setuptools==69.5.1 in .\venv\Lib\site-packages (69.5.1)
Note: you may need to restart the kernel to use updated packages.