In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [8]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [10]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

## ANN Regression Problem Statement

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [16]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 100377.0625 - mae: 100377.0625 - val_loss: 98515.7969 - val_mae: 98515.7969
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 99616.8047 - mae: 99616.8047 - val_loss: 96968.4609 - val_mae: 96968.4609
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 96916.9453 - mae: 96916.9453 - val_loss: 93005.1797 - val_mae: 93005.1797
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 91597.3594 - mae: 91597.3594 - val_loss: 86392.1172 - val_mae: 86392.1172
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 83844.0859 - mae: 83844.0859 - val_loss: 77892.6875 - val_mae: 77892.6875
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 74741.4062 - mae: 74741.4062 - val_loss: 69022.0391 - val_mae: 69022.0391
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 65840.6875 - mae: 65840.6875 - val_loss: 61296.9961 - val_mae: 61296.9961
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 58746.4297 - mae: 58746.4297 - val_loss: 55818.1914 - val_mae: 55818.1914
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 54151.6602 - mae: 54151.6602 - val_loss: 52768.4102 - val_mae: 52768.4102
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 51713.2461 - mae: 51713.2461 - val_loss: 51488.5273 - val_mae: 51488.5273
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50691.5664 - mae: 50691.5664 - val_loss: 51077.3711 - val_mae: 51077.3711
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50331.5234 - mae: 50331.5234 - val_loss: 50937.7734 - val_mae: 50937.7734
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50199.4141 - mae: 50199.4141 - val_loss: 50879.1172 - val_mae: 50879.1172
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50119.4766 - mae: 50119.4766 - val_loss: 50827.5625 - val_mae: 50827.5625
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50058.5430 - mae: 50058.5430 - val_loss: 50780.6055 - val_mae: 50780.6055
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50010.5547 - mae: 50010.5547 - val_loss: 50738.8828 - val_mae: 50738.8828
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 49965.0938 - mae: 49965.0938 - val_loss: 50703.5195 - val_mae: 50703.5195
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 49928.9688 - mae: 49928.9688 - val_loss: 50673.0586 - val_mae: 50673.0586
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49895.4961 - mae: 49895.4961 - val_loss: 50638.9922 - val_mae: 50638.9922
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 49863.0898 - mae: 49863.0898 - val_loss: 50617.4727 - val_mae: 50617.4727
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 49834.3203 - mae: 49834.3203 - val_loss: 50593.3086 - val_mae: 50593.3086
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49804.6875 - mae: 49804.6875 - val_loss: 50572.2305 - val_mae: 50572.2305
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49780.9219 - mae: 49780.9219 - val_loss: 50550.0430 - val_mae: 50550.0430
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49761.8086 - mae: 49761.8086 - val_loss: 50533.6758 - val_mae: 50533.6758
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49737.2695 - mae: 49737.2695 - val_loss: 50523.2383 - val_mae: 50523.2383
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49714.1758 - mae: 49714.1758 - val_loss: 50498.0195 - val_mae: 50498.0195
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49695.4492 - mae: 49695.4492 - val_loss: 50490.6914 - val_mae: 50490.6914
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49677.1367 - mae: 49677.1367 - val_loss: 50475.1211 - val_mae: 50475.1211
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49663.0625 - mae: 49663.0625 - val_loss: 50461.8711 - val_mae: 50461.8711
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49644.9258 - mae: 49644.9258 - val_loss: 50449.5469 - val_mae: 50449.5469
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49629.4727 - mae: 49629.4727 - val_loss: 50437.3125 - val_mae: 50437.3125
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49619.0547 - mae: 49619.0547 - val_loss: 50438.9023 - val_mae: 50438.9023
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49602.6328 - mae: 49602.6328 - val_loss: 50428.2031 - val_mae: 50428.2031
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49587.6641 - mae: 49587.6641 - val_loss: 50430.9023 - val_mae: 50430.9023
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49577.4414 - mae: 49577.4414 - val_loss: 50415.5938 - val_mae: 50415.5938
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49565.5977 - mae: 49565.5977 - val_loss: 50416.4141 - val_mae: 50416.4141
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49561.6016 - mae: 49561.6016 - val_loss: 50408.8281 - val_mae: 50408.8281
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49548.5781 - mae: 49548.5781 - val_loss: 50409.0703 - val_mae: 50409.0703
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49540.7617 - mae: 49540.7617 - val_loss: 50405.7969 - val_mae: 50405.7969
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49530.0312 - mae: 49530.0312 - val_loss: 50397.2227 - val_mae: 50397.2227
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49520.9414 - mae: 49520.9414 - val_loss: 50392.1914 - val_mae: 50392.1914
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49515.5352 - mae: 49515.5352 - val_loss: 50390.5469 - val_mae: 50390.5469
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49508.7383 - mae: 49508.7383 - val_loss: 50384.5508 - val_mae: 50384.5508
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49496.9492 - mae: 49496.9492 - val_loss: 50386.6680 - val_mae: 50386.6680
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49489.6680 - mae: 49489.6680 - val_loss: 50388.8203 - val_mae: 50388.8203
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49481.7969 - mae: 49481.7969 - val_loss: 50385.9688 - val_mae: 50385.9688
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49473.8438 - mae: 49473.8438 - val_loss: 50390.4297 - val_mae: 50390.4297
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49470.9062 - mae: 49470.9062 - val_loss: 50396.5469 - val_mae: 50396.5469
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49461.1445 - mae: 49461.1445 - val_loss: 50398.1016 - val_mae: 50398.1016
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49454.1875 - mae: 49454.1875 - val_loss: 50388.2383 - val_mae: 50388.2383
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49451.4414 - mae: 49451.4414 - val_loss: 50378.6836 - val_mae: 50378.6836
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49439.4609 - mae: 49439.4609 - val_loss: 50390.2656 - val_mae: 50390.2656
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49436.2773 - mae: 49436.2773 - val_loss: 50395.3203 - val_mae: 50395.3203
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49430.4375 - mae: 49430.4375 - val_loss: 50395.6250 - val_mae: 50395.6250
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49423.1562 - mae: 49423.1562 - val_loss: 50383.1562 - val_mae: 50383.1562
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49418.8320 - mae: 49418.8320 - val_loss: 50390.5078 - val_mae: 50390.5078
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49415.5391 - mae: 49415.5391 - val_loss: 50383.1289 - val_mae: 50383.1289
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 49410.6641 - mae: 49410.6641 - val_loss: 50395.3867 - val_mae: 50395.3867
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 49401.7031 - mae: 49401.7031 - val_loss: 50386.4492 - val_mae: 50386.4492
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49395.9375 - mae: 49395.9375 - val_loss: 50377.0938 - val_mae: 50377.0938
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 49392.4883 - mae: 49392.4883 - val_loss: 50381.0664 - val_mae: 50381.0664
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 49388.3516 - mae: 49388.3516 - val_loss: 50386.8633 - val_mae: 50386.8633
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49383.1445 - mae: 49383.1445 - val_loss: 50382.4648 - val_mae: 50382.4648
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 49379.5430 - mae: 49379.5430 - val_loss: 50391.3555 - val_mae: 50391.3555
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 49374.5586 - mae: 49374.5586 - val_loss: 50389.8164 - val_mae: 50389.8164
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 49369.2031 - mae: 49369.2031 - val_loss: 50395.1250 - val_mae: 50395.1250
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 49365.5273 - mae: 49365.5273 - val_loss: 50396.2305 - val_mae: 50396.2305
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 49360.1758 - mae: 49360.1758 - val_loss: 50394.7930 - val_mae: 50394.7930
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 49358.9062 - mae: 49358.9062 - val_loss: 50404.9922 - val_mae: 50404.9922
Epoch 70/100
250/250 [==============================] - 1s 2ms/step - loss: 49354.5117 - mae: 49354.5117 - val_loss: 50398.0273 - val_mae: 50398.0273

In [20]:
%load_ext tensorboard

In [21]:
%tensorboard --logdir regressionlogs/fit

In [22]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 1ms/step - loss: 50377.0938 - mae: 50377.0938
Test MAE : 50377.09375

In [23]:
model.save('regression_model.h5')

e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(