In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

## ANN Regression Problem Statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 3ms/step - loss: 100373.9297 - mae: 100373.9297 - val_loss: 98504.5781 - val_mae: 98504.5781
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99594.2812 - mae: 99594.2812 - val_loss: 96931.7266 - val_mae: 96931.7266
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 96821.9922 - mae: 96821.9922 - val_loss: 92819.0469 - val_mae: 92819.0469
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 91315.9297 - mae: 91315.9297 - val_loss: 85973.0938 - val_mae: 85973.0938
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 83295.6094 - mae: 83295.6094 - val_loss: 77164.3828 - val_mae: 77164.3828
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 74022.1953 - mae: 74022.1953 - val_loss: 68117.1406 - val_mae: 68117.1406
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 65129.3008 - mae: 65129.3008 - val_loss: 60349.1250 - val_mae: 60349.1250
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 58133.3242 - mae: 58133.3242 - val_loss: 54904.3086 - val_mae: 54904.3086
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 53787.1797 - mae: 53787.1797 - val_loss: 51948.4023 - val_mae: 51948.4023
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 51619.6289 - mae: 51619.6289 - val_loss: 50776.3398 - val_mae: 50776.3398
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50738.0000 - mae: 50738.0000 - val_loss: 50411.9492 - val_mae: 50411.9492
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50397.0391 - mae: 50397.0391 - val_loss: 50323.2109 - val_mae: 50323.2109
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50262.5039 - mae: 50262.5039 - val_loss: 50305.6133 - val_mae: 50305.6133
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 50189.1875 - mae: 50189.1875 - val_loss: 50297.8867 - val_mae: 50297.8867
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50133.0117 - mae: 50133.0117 - val_loss: 50278.8594 - val_mae: 50278.8594
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50089.4922 - mae: 50089.4922 - val_loss: 50258.9258 - val_mae: 50258.9258
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 50051.2461 - mae: 50051.2461 - val_loss: 50231.8750 - val_mae: 50231.8750
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 50019.8320 - mae: 50019.8320 - val_loss: 50203.7969 - val_mae: 50203.7969
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49989.2812 - mae: 49989.2812 - val_loss: 50189.1641 - val_mae: 50189.1641
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 49960.8633 - mae: 49960.8633 - val_loss: 50198.5430 - val_mae: 50198.5430
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 49933.8086 - mae: 49933.8086 - val_loss: 50172.5352 - val_mae: 50172.5352
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49911.0859 - mae: 49911.0859 - val_loss: 50156.7109 - val_mae: 50156.7109
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49882.4336 - mae: 49882.4336 - val_loss: 50151.2383 - val_mae: 50151.2383
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49861.2344 - mae: 49861.2344 - val_loss: 50160.9102 - val_mae: 50160.9102
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 49841.0508 - mae: 49841.0508 - val_loss: 50139.9492 - val_mae: 50139.9492
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49819.6094 - mae: 49819.6094 - val_loss: 50137.4609 - val_mae: 50137.4609
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49805.4570 - mae: 49805.4570 - val_loss: 50138.3438 - val_mae: 50138.3438
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49782.5352 - mae: 49782.5352 - val_loss: 50140.4219 - val_mae: 50140.4219
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49768.0156 - mae: 49768.0156 - val_loss: 50127.7305 - val_mae: 50127.7305
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49756.8789 - mae: 49756.8789 - val_loss: 50120.4062 - val_mae: 50120.4062
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49737.5430 - mae: 49737.5430 - val_loss: 50124.7188 - val_mae: 50124.7188
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49720.2734 - mae: 49720.2734 - val_loss: 50114.0781 - val_mae: 50114.0781
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 49705.9023 - mae: 49705.9023 - val_loss: 50111.1094 - val_mae: 50111.1094
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49693.1836 - mae: 49693.1836 - val_loss: 50112.2227 - val_mae: 50112.2227
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49682.3516 - mae: 49682.3516 - val_loss: 50104.8359 - val_mae: 50104.8359
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49666.0273 - mae: 49666.0273 - val_loss: 50105.2773 - val_mae: 50105.2773
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49653.5977 - mae: 49653.5977 - val_loss: 50099.9805 - val_mae: 50099.9805
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49644.4258 - mae: 49644.4258 - val_loss: 50105.3789 - val_mae: 50105.3789
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49632.7305 - mae: 49632.7305 - val_loss: 50102.6719 - val_mae: 50102.6719
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49625.2930 - mae: 49625.2930 - val_loss: 50090.4844 - val_mae: 50090.4844
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49610.2812 - mae: 49610.2812 - val_loss: 50094.8594 - val_mae: 50094.8594
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49605.2188 - mae: 49605.2188 - val_loss: 50102.6445 - val_mae: 50102.6445
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49591.4570 - mae: 49591.4570 - val_loss: 50102.6602 - val_mae: 50102.6602
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49581.9531 - mae: 49581.9531 - val_loss: 50098.9844 - val_mae: 50098.9844
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49572.6602 - mae: 49572.6602 - val_loss: 50100.1992 - val_mae: 50100.1992
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49561.8750 - mae: 49561.8750 - val_loss: 50105.5977 - val_mae: 50105.5977
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49554.8125 - mae: 49554.8125 - val_loss: 50107.2734 - val_mae: 50107.2734
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 49543.3398 - mae: 49543.3398 - val_loss: 50109.8398 - val_mae: 50109.8398
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49535.9414 - mae: 49535.9414 - val_loss: 50111.2344 - val_mae: 50111.2344
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 49527.6328 - mae: 49527.6328 - val_loss: 50121.8516 - val_mae: 50121.8516

In [22]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
%reload_ext tensorboard

In [36]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 8004), started 17:54:58 ago. (Use '!kill 8004' to kill it.)

In [35]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 949us/step - loss: 50090.4844 - mae: 50090.4844
Test MAE : 50090.484375

In [20]:
model.save('regression_model.h5')

e:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(